INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ADAPTATIVE_FILTERING adaptative_filtering)

FIND_PATH(
    ADAPTATIVE_FILTERING_INCLUDE_DIRS
    NAMES adaptative_filtering/api.h
    HINTS $ENV{ADAPTATIVE_FILTERING_DIR}/include
        ${PC_ADAPTATIVE_FILTERING_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ADAPTATIVE_FILTERING_LIBRARIES
    NAMES gnuradio-adaptative_filtering
    HINTS $ENV{ADAPTATIVE_FILTERING_DIR}/lib
        ${PC_ADAPTATIVE_FILTERING_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ADAPTATIVE_FILTERING DEFAULT_MSG ADAPTATIVE_FILTERING_LIBRARIES ADAPTATIVE_FILTERING_INCLUDE_DIRS)
MARK_AS_ADVANCED(ADAPTATIVE_FILTERING_LIBRARIES ADAPTATIVE_FILTERING_INCLUDE_DIRS)

